# Generated by Django 5.1.1 on 2024-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parselogs',
            name='url',
        ),
        migrations.AddField(
            model_name='parselogs',
            name='uri',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URI'),
        ),
    ]
